load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "english_thesaurus",
    srcs = [
        "english_thesaurus.py",
        "main.py"
        ],
    main = "main.py",
    data = ["data.json"],
)
